CreateTest/Controllers/ListController.cs
using CreateTest.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CreateTest.Controllers
{
    public class ListController : Controller
    {
        private myDbContext db;
        private UserManager<ApplicationUser> manager;

        public ListController()
        {
            db = new myDbContext();
            manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
        }

        public ActionResult Index()
        {
            return View(db.TopTenList.ToList());
        }

        // GET: List
        public ActionResult Create()
        {            
            return View(new TopTenList());
        }

        [HttpPost]
        public ActionResult Create(TopTenList lmodel, IEnumerable<ListItem> items, IEnumerable<HttpPostedFileBase> file1, HttpPostedFileBase file)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());
            
            if (ModelState.IsValid)
            {
                lmodel.ListItems = items;
                lmodel.AspNetUser = currentUser;

                using (var br = new BinaryReader(file.InputStream))
                {
                    var data = br.ReadBytes(file.ContentLength);
                    lmodel.Image = data;
                }

                    db.TopTenList.Add(lmodel);

                var imageList = new List<object>();
                foreach (var j in file1)
                {
                    using (var br = new BinaryReader(j.InputStream))
                    {
                        var data = br.ReadBytes(j.ContentLength);
                        imageList.Add(data);
                    }
                }
                var count = 0;
                foreach (var i in items)
                {
                    i.Image = (byte[])imageList[count];
                    i.TTList = lmodel;
                    db.List_Items.Add(i);
                    count++;
                }

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(lmodel);
        }       

        public ActionResult Details(int? id)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());
            var obj = db.UserRatedLists.Where(m => m.List.ID == id && m.User.Id == currentUser.Id).ToList();

            List<object> myModel = new List<object>();

            myModel.Add(db.TopTenList.Where(m => m.ID == id).ToList());
            myModel.Add(db.List_Items.Where(m => m.TTList.ID == id).OrderByDescending(m => m.Rating).ToList());
            myModel.Add(obj);
            myModel.Add(db.Comments.Where(m => m.TTList.ID == id).ToList());

            return View(myModel);
        }
        //----------------------------------------------------------------
        [HttpPost]
        public ActionResult Comment(int ListID, string text)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                var comment = new Comment();
                comment.AspNetUser = currentUser;
                comment.CommentContent = text;
                comment.SharedOn = DateTime.Now;
                comment.isPublished = true;
                comment.TTList.ID = ListID;

                db.Comments.Add(comment);
                db.SaveChanges();
            }
            return RedirectToAction("ListView");
        }

        public ActionResult Rate(int? itemid, string userid)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());
            Rated rated = new Rated();
            var listItem = db.List_Items.Find(itemid);
            var obj = db.RatedList.Where(r => r.ListItem.ID == (int)itemid && r.User.Id == currentUser.Id).ToList();

            if(obj.Count == 0)
            {
                ListUserHasRated luhr = new ListUserHasRated();                

                rated.ListItem = listItem;
                rated.User = currentUser;
                listItem.Rating += 1;
                luhr.List = db.TopTenList.Find(listItem.TTList.ID);
                luhr.User = currentUser;
                db.UserRatedLists.Add(luhr);
                db.RatedList.Add(rated);
                db.SaveChanges();
                return Redirect("Index");
            }
            else
            {
                return View(obj);
            }

            
        }

        public bool userHasVotedOnThisList (int? ListId)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());
            var list = db.TopTenList.Find(ListId);

            var obj = db.UserRatedLists.Where(r => r.User == currentUser && r.List == list).ToList();
            if (obj == null)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        


        ///-------------------------------------------------------------------

    }
}

CreateTest/Views/List/Create.cshtml
@model CreateTest.Models.TopTenList

@{
    ViewBag.Title = "Create";
}

<h2>Index</h2>

@using (Html.BeginForm("Create","List",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        List Title @Html.TextBox("Title", Model.Title) <br /><br />
        List Desc @Html.TextBox("description", Model.Description) <br /><br />
        Votable @Html.CheckBox("isVotable",Model.isVotable)<br /><br />
        <input class="form-control col-md-2" type="file" id="file" name="file" multiple="multiple" required /> <br />
        <table>
            <tr>
                <th>Item TItle</th>
                <th>ITem Descr</th>
            </tr>
            @{
                for (int i = 0; i < 3; i++)
                {
                    <tr>
                        <td> @Html.TextBox("[" + i + "].Title") </td>
                        <td> @Html.TextBox("[" + i + "].Description")</td>
                        <td><input class="form-control col-md-2" type="file" id="file1" name="file1" multiple="multiple" required /> <br /></td>
                    </tr>
                }
            }
        </table>

        <input type="submit" value="Submit" /> <br /><br />



    </div>
                }

CreateTest/Views/List/Details.cshtml
@model IEnumerable<object>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_hydrogen.cshtml";
    List<CreateTest.Models.TopTenList> TopTenLists = Model.ToList()[0] as List<CreateTest.Models.TopTenList>;
    List<CreateTest.Models.ListItem> ListItems = Model.ToList()[1] as List<CreateTest.Models.ListItem>;
    List<CreateTest.Models.ListUserHasRated> listRated = Model.ToList()[2] as List<CreateTest.Models.ListUserHasRated>;
    List<CreateTest.Models.Comment> comments = Model.ToList()[3] as List<CreateTest.Models.Comment>;
    int id = 0;
    var isvotable = false;
}

<div class="container">
    <div  class="row">
        <div class="col-md-12 text-center">
            @foreach (var item in TopTenLists)
            {
                string image = Convert.ToBase64String(item.Image);
                string imgsrc = string.Format("data:image/gif;base64,{0}", image);
                <img src="@imgsrc" class="img-responsive"/>                
            }            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @foreach (var item in TopTenLists)
            {
                <h1>@item.Title</h1>
                <p style="color:darkgray">Posted by: @item.AspNetUser.UserName</p>
                <br />
                <h3>Description</h3>
                <p>@item.Description</p>
            }
        </div>
    </div>
</div>

<hr />

<div id="list-items">
    <div class="container">
        @foreach (var item in ListItems) {
        <div class="row">
            <div class="col-xs-3 " style="width:100px;height:100px;">
                @{
                    string imageBase64 = Convert.ToBase64String(item.Image);
                    string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                    <img style="" class="img-responsive img-thumbnail" src="@imageSrc" />
                }
            </div>
            <div style="border:none; background:white;" class="col-md-8 col-xs-8 col-md-offset-1 col-xs-offset-1" >
                <h3>@item.Title <span class="votes-html" style="color:darkgray">| Votes:@item.Rating</span></h3>
                <p>@item.Description</p>
                @{
                    foreach (var i in TopTenLists)
                    {
                        if (i.isVotable == true)
                        {
                            @Html.ActionLink("UpVote", "Rate", new { itemid = item.ID, userid = i.AspNetUser.Id }, new { @class = "vote-link" });
                        }
                    }
                }
                
            </div>            
        </div>
        <br />
                    }
    </div>
</div>

<div id="comment">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                @foreach (var item in TopTenLists)
                {
                    //Html.ActionLink("CommentAction", "List", new { ListId = item.ID, comment = texg })
                    Html.RenderPartial("~/Views/Comment/Comment.cshtml",new CreateTest.Models.Comment(), new ViewDataDictionary { { "ListId", item.ID } });
                    //Html.RenderPartial("~/Views/Shared/_test.cshtml", null, new ViewDataDictionary { { "ListId", item.ID } });
                }
                
            </div>
        </div>
    </div>
</div>

<div id="all-comments">
    <div class="container">
        @foreach(var item in comments)
        {
            <div class="row">
                <div class="col-md-12">
                    <h4>@item.AspNetUser.UserName</h4>
                    <p>@item.SharedOn</p>
                    <p>@item.CommentContent</p>
                </div>
            </div>
        }
    </div>
</div>

@{if (listRated.Count != 0)
    {
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous">

        </script>
        <script>
            $(document).ready(function () {
                $(".vote-link").remove();
            });
        </script>
    }
    
    }

@foreach(var item in TopTenLists)
{
     
        isvotable = item.isVotable;
       
}

@if (isvotable == false)
{
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous">

    </script>
    <script>
        $(document).ready(function () {
            $(".votes-html").remove();
        });
    </script>
    
}



@*<div class="container">
    <div class="row">
        @foreach (var item in TopTenLists)
        {


            <div class="col-md-12 text-center">
                @{
                    string imageBase64 = Convert.ToBase64String(item.Image);
                    string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                    <img class="img-responsive text-center" src="@imageSrc" />
                }
                <h1>@item.Title</h1>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p>@item.Description</p>
                </div>
            </div>

                    }
    </div>
    
</div>*@

@*<hr />*@

@*<h3>List Items</h3>
<ul>
    @foreach (var item in ListItems)
    {
        <li>@item.Title</li>
        <li>@item.Description</li>
    }
</ul>*@

@*<div id="list-items">
    <div class="container">
@foreach (var item in ListItems)
{
        <div class="row">
            
                <div style="max-height:300px;" class="col-md-3">
                    @{
                        string imageBase64 = Convert.ToBase64String(item.Image);
                        string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                        <img style="padding-bottom:100px;" class="img-thumbnail img-responsive" src="@imageSrc" />
                    }
                </div>
                <div class="col-md-8 col-md-offset-1">                     
                        <h3>@item.Title</h3>
                        <p>@item.Description</p>                    
                </div>
            
        </div>
                        }
    </div>
</div>*@

CreateTest/Views/List/Index.cshtml
@model IEnumerable<CreateTest.Models.TopTenList>
@{      
    Layout = "~/Views/Shared/_hydrogen.cshtml";
}

<div id="fh5co-main">
    <div class="container">

        <div class="row">

            <div id="fh5co-board" data-columns>
                @foreach (var item in Model)
                {
                    <div class="item">
                        <div class="animate-box">
                            <a href="@Url.Content("~/Content/hydrogen/")images/img_1.jpg" class="image-popup fh5co-board-img" title="@item.Title">                                
                                @{ 
                                    string base64 = Convert.ToBase64String(item.Image);
                                    string imgsrc = string.Format("data:image/gif;base64,{0}", base64);
                                    <img src="@imgsrc"/>
                                }
                            </a>
                        </div>
                        <div class="fh5co-desc"><h4><a style="text-decoration:none;" href="@(Url.Action("Details","List",new { id = item.ID}))"><strong>@item.Title</strong></a></h4>@item.Description</div>
                    </div>
                }
                                                
            </div>
        </div>
    </div>
</div>

CreateTest/Views/List/Rate.cshtml
@model IEnumerable<CreateTest.Models.Rated>
@{
    ViewBag.Title = "Rate";
    Layout = "~/Views/Shared/_hydrogen.cshtml";
}

<h2>Rate</h2>

@foreach(var item in Model)
{
    <p>@item.ID</p>
    <p>@item.ListItem.ID</p>
    <p>@item.ListItem.Title</p>
    <p>@item.User.Id</p>
}